#what this yml file is going to denote
name: Go CI/CD
#on which events these jobs be triggered
#push and pull are childrens of on so we have to maintain the indetation as well
on:
  push:
    branches:
      - day-9
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    #which particular machine should github use in their servers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        #it tells github to checkout to the current branch
        uses: actions/checkout@v4

      - name: Set up Go
        #we have to create go environment before doing anything else
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        #install all the dependencies
      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o master
      

      # - name: Run GoLinters
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.55
      #     args: --timeout=5m
      #     skip-cache: true
